---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: defaults
spec:
  configPatches:
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: en0
            dhcp: true
            vip:
              ip: 10.0.14.2
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: true
    - op: add
      path: /machine
      value:
        pxeBootAlways: true
