---
apiVersion: metal.sidero.dev/v1alpha1
kind: ServerClass
metadata:
  name: work-pc
spec:
  qualifiers:
    systemInformation:
      - manufacturer: Dell Inc.
        productName: SPrecision WorkStation T3500
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sdb
    - op: add
      path: /machine/network
      value:
        interfaces:
          - interface: enp5s0
            dhcp: true
            vip:
              ip: 10.0.14.2
