---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: blookums
  namespace: flux-system
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
    kind: TalosControlPlane
    name: blookums-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
    kind: MetalCluster
    name: blookums
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha3
kind: MetalCluster
metadata:
  name: blookums
  namespace: flux-system
spec:
  controlPlaneEndpoint:
    host: 10.0.14.2
    port: 6443
