---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
  - nodefeaturerule.yaml
configMapGenerator:
  - name: frigate-configmap
    namespace: home
    files:
      - ./config.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
