---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_GATE_MYSQL_PATH}
    server: ${SECRET_FILESERV_IP}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql
  namespace: gate
spec:
  storageClassName: ''
  volumeName: mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
