---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: security-camera
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_SECURITY_CAMERA_PATH}
    server: ${SECRET_FILESERV_IP}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: security-camera
  namespace: gate
spec:
  storageClassName: ''
  volumeName: security-camera
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
