# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-management
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:bt9wPwThX8mrODdjonY=,iv:Hf+80ziiBfI1m/kZaj6+ra/O6p2ynTt5NQbQaNEok40=,tag:Ovt5pkkXGqpLFjcT0Ku/oQ==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:gP2T2CYt/9hjRjM0lK/Bt2TfTkr34+HFTYFzDq+78dWuxYsJvfdwygH3x/XfUPr++iOPlkuxJT3X1l0/BvkYg03kxnjJApy5LZQgaidcF5doRuekE9IjnBTS/dNTssz/XD1tBpdGOZf5JYMbiSqd5q/HSEY8vLD8dA==,iv:x5JaBEdcXfUkJWDzT14d/fl+YNySE0Y6HPIZw8e3xT0=,tag:67Vr3TOVNBUk+CTaxPLwmQ==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:T3LGTFQDSZvEp79D8OKnc4SVpw==,iv:4wbZPnY1NCOPykNEzDK2SMOObKNsjdTFqE0mwQ6+VUw=,tag:t6hhKAAkCWmkoCLMMUidDQ==,type:str]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:5geOMkFRb37UvR9f6+eXVZAsHQ==,iv:LGGs62DT9dPCCfnSI5lInhyrHDinOooawrQ0gebE7gU=,tag:18gK59E7wIuKGLZ9i0XqNg==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:1FUkj0drXB9U5BHyHpHrGi7bnK1vrXCkKFR7WZLl4fxFH0JZBsevWvYDnSAwoIB0rcpR44yPqDPmLQcZ7kQfmjlzbNyg1eYP,iv:tavIQQmd0R3gue9EPFfp8duQKkRkpO/rPAbllF/lbFs=,tag:65mDpLba9HTEEUK8OazuRw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:yz/iIgDkygQRMTysbre9XShVQEh1,iv:PoIrWefgVqU7f9YA996Qep9DMKcRkG2KH/bB2aw1uv4=,tag:yf0bzp9/ne70fGmI5QevGg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:Sh/1Pn14FyP0bEZ9y4vz0Y6LiVM=,iv:SodbR3DnWrNuAFfow+HvdTQgy/FjoZdDrnqys9Irz84=,tag:H/SM7+aGpSYW/KyPoe+rAA==,type:str]
    SECRET_DOGBERT_IPMI_PASSWORD: ENC[AES256_GCM,data:nobN88DseSRCVms=,iv:nYO6kqn2LcHfL7S0Te5h3DTiCGYmZ3EG7MacAo71TFM=,tag:yLJk+te8K/l9tG1cu42EdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb0dpQXVObjExdGR6ZmFO
            Rlg0U3FyalVrMnByYUtXa2hzQ2lISlRyMkE0CnZEc05iRXFEekZnc3NSSi9DSVpJ
            cjEzaFZ5ZnM2QlJ3QlBOSk5idktZR28KLS0tIHN6NU1wc2hhTzlsS1lHOHN5THBY
            UWNCbHRzdjZUWUppdFAxYUZWSVJtanMKxxKC44jnjRhqyUCgsx9mlqNrUc07BM4T
            XoBjcUi1fuyXcAxfe9JtvwNIAsdi0KID6MzuL5ZjYUGuavrnWfvluQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-10T09:21:18Z"
    mac: ENC[AES256_GCM,data:0LmbXys75aDmrUwjKXhVjF5WKEZiNAZhyA4pRjzATBZgxmsYl9/E1R16cVrLVdG2YTw1mAYMubcDq0R9YPGrhAKwBibUTroiViPhF3/E54r64Z7RMomNwnEPGkQQymr6z6GGXGzKOBHrzYQHuXWlPMjbguyCaEszp62V2rzbjfk=,iv:/79NkfC/0Aa7SsmqbOzC1o5jdioicXKFnU4CUKOame4=,tag:wLhTLv0rImI/GJ48yIta4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
