---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings-management
  namespace: flux-system
data:
  GATEWAY_IP: 10.0.16.1
  SVC_HOME_ASSISTANT_ADDRESS: 192.168.1.246
  SVC_PROMTAIL_ADDRESS: 192.168.1.243
