---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: plex
  namespace: media
spec:
  interval: 5m
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: plex
      version: 6.4.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    initContainers:
      update-volume-permission:
        command:
          - sh
          - -c
          - chown -R 568:568 /config
        image: busybox
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /config
            name: config
    image:
      repository: ghcr.io/onedr0p/plex
      tag: 1.30.0.6486-629d58034@sha256:b3e3a2a305443f243643553161cff639f3dcc74349595884ac9c77cf6bb24068
    env:
      TZ: America/New_York
      ADVERTISE_IP: 192.168.11.6
    service:
      main:
        primary: true
        ports:
          http:
            port: 32400
        type: LoadBalancer
        externalTrafficPolicy: Local
    persistence:
      config:
        enabled: true
        storageClass: ceph-hdd
        size: 1Ti
      movies:
        enabled: true
        type: pvc
        existingClaim: movies
      tv:
        enabled: true
        type: pvc
        existingClaim: tv
    podAnnotations:
      backup.velero.io/backup-volumes: config

    resources:
      requests:
        cpu: 1000m
        memory: 1000Mi
      limits:
        memory: 24000Mi
