---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: incoming-sabnzbd
  namespace: media
spec:
  storageClassName: ""
  volumeName: incoming-sabnzbd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
