---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: incoming-mp3-sabnzbd
  namespace: media
spec:
  storageClassName: ''
  volumeName: incoming-mp3-sabnzbd
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
