---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: incoming-sabnzbd
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_INCOMING_PATH}
    server: ${SECRET_FILESERV_IP}
