---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets-blookums
  namespace: flux-system
stringData:
  SECRET_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:gDqXbFSpXALxBruXWVCi9tiYgDg=,iv:lqCfaWciyIp662Y5T1NDAvnYThLfLadPWjHfzys2gKI=,tag:JHG+K92XCZO1oPZO4wyjOw==,type:str]
  SECRET_AWS_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:sbAGPG9rBsaociMR+OKZa50lWoG+Cgs0trdhb5m+NqPFxInBuwI9YQ==,iv:hA8PW3RuT6bxRyMLj4FBnZZba42Rk0Ccoo8Gh/pOWjA=,tag:tKmAupJlA1Yh4llJo14/tQ==,type:str]
  SECRET_AWS_BUCKET_NAME: ENC[AES256_GCM,data:JxK7OrIVB0wqU/2Ro5rtObI=,iv:euI6faa8GQdhjfYCMQXTy0wE//Vi8Vp7yra9EIFzWxk=,tag:v0arlFg4U6aS03bZOq5n/Q==,type:str]
  SECRET_AWS_REGION: ENC[AES256_GCM,data:0n1lInvIDA58,iv:RjAkG7fgFm6WZDRMwMi0zGoumwI7wsvUhk7j64nMygQ=,tag:av3y7yskU1UyPn/B2XTbjA==,type:str]
  SECRET_AUTH_URL: ENC[AES256_GCM,data:PR8DGLIbgWVIGuYZqNN/Sp1oZPFYqYwG2x/kOW10BnWbJqcwDPPFzw==,iv:swuxeDYOIewYGAptsJiPgaaWCx09HgeD9m5h07LBLOM=,tag:4uOHCeCeEOoS72v+pr4b7Q==,type:str]
  SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:eCMbO6kuLjZz62cic/qcFTQouVC5u1lKii5LINI5VstM+5tG1KgGlQ/RfIhlvU7f4M8vKGd5TZ56AqScGD9pDm5ewNymGrE+2bee9p03EEkB8vYeAS/4Z1LinDrVwZFGlKtKdcjhsWFpjhOsIKu9ThRaJigYmG44Wg==,iv:Y4QfxBRqOkgL+qWbvratHvm89nFtYk7V/PbrkjqFfNs=,tag:Srxn2QExj/6V0rAaZnv68w==,type:str]
  SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:KiGLf5CEmuj4lX+94oI0XI2J7g==,iv:CiFZNVmnBolroPD0/88/rRmEHlixL1SkwPnKhxgL4aE=,tag:79eGwM4rgFO0C9ct4VE3pA==,type:str]
  SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:DRQD5eXqSJMgDspzjwnivf0iVw==,iv:vbJvmr+9pXFON28Q7pFclM80ZMoGSXFuWQ5yTeoNzhQ=,tag:eevXdNUruA6vJ+tq77PjnQ==,type:str]
  SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:kXqhgMQeRy3JJk6iFMmbu+GYf2//+cq+cbqRGX2rWx+2ajtIpqcjj34/JFHKLXcNHsZjCtzmHahQN90tc/qrcR0h1ue+AFUv,iv:rosm80cbI5N1ylOI0F+E+e184W3bHSe47aYwDI5CmP4=,tag:bKOPCYgv0NWvK/cAIvpgyA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:olcgndx/Ngf/F8G4B0Q=,iv:pdNzuv1ubH8HfMy1dAJguW5iUVgaqvc3MwmBjDa417I=,tag:wTbjx4Pn9Mmfk1I7yMcflg==,type:str]
  SECRET_EMAIL: ENC[AES256_GCM,data:W8jhBBj8+KMG/WmMK0XoP/zh986p,iv:UUty8muAtEbmdb8dWP0kzupO3nnERzTR9/yjWiRRHAc=,tag:2ofM7tKT7CpulHNU319u3w==,type:str]
  SECRET_FILESERV_IP: ENC[AES256_GCM,data:/CwapRoMMSiT,iv:m+E/aJas6/KnALW5RWB1IaJvz7QFcfx887xJAc1xAe8=,tag:YkArc7l4TATkZfqEuzW4pA==,type:str]
  SECRET_FILESERV_MOVIE_PATH: ENC[AES256_GCM,data:9lc81YB3Vr9v3bhHemC9ALEEjY8Ts24icXbfnrta7QBerZM=,iv:2cMrFz6wjIMW+h+q5iKq+wc0IcVIHnAUTdrcpX3d4C8=,tag:y8dPDVnhi5LVLCdSs4H4iw==,type:str]
  SECRET_FILESERV_TV_PATH: ENC[AES256_GCM,data:8O4khXD306N+cLinPjdoaenXyMe/2hcKXTFYNAr8Vw==,iv:N42nNYazbwMumdE/GxMHgD+hC/kIiAWvVK8UyZGldrg=,tag:g769kNVC/PIFz74muymVIw==,type:str]
  SECRET_FILESERV_INCOMING_PATH: ENC[AES256_GCM,data:ebar3h1e9qYl5PPMuXu/vysUM7IvMMwPyEVxtAVoeV8FRzTyaA==,iv:tzNwuglp677BB3bM76GklnQa+TCvr478yiNIkwu92pI=,tag:zNDNyI0Djcz1yoLYmeiGng==,type:str]
  SECRET_FILESERV_INCOMING_MP3_PATH: ENC[AES256_GCM,data:DuNGzpjysiVMGO20XkbwXwK9nnAB2XcoEhF9RpUIQvs=,iv:BrlMDiC8QtfVIAkUv77f4MfF66dpYb9hLPOgsPJrHKQ=,tag:aMQr28GSkABuB0uX/Ffhxw==,type:str]
  SECRET_FILESERV_INCOMING_MOVIE_PATH: ENC[AES256_GCM,data:n5PeWwom1ipo9wcqXTUjf0o7IP2LH+hiCdwiISVgLMQ9NrB2TweviUXnczQ=,iv:8oWAp1wxYPNSoG2pfJhKIJ2Kr1alh1hEEH9DOMbYYfQ=,tag:jqPKWZOp9h0bU9dDO+YtMg==,type:str]
  SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:H5E2MZg+IvazeGeXz+gvr3V8tSc=,iv:xWuxxGdfv8e7NpJ9z2oiPBfMuvxEM5DX5dmTX3D4agU=,tag:CehaL1lIyJhBK/zpe1BOVA==,type:str]
  SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:hRbvI3PI4Y8=,iv:d850HAtqt8o657tgblpMOtCBvomZLXvi1Ke9BQND9cY=,tag:Qz4UjKPexV+AGlRYoHtFcw==,type:str]
  SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:kkt0eQ51,iv:b+S1rX4CkkrrsSq1IyF5kJ13UsYFy5hX+VJOqKs8HIM=,tag:Y/Fy05yKcFouw+pj2AcmyQ==,type:str]
  SECRET_MQTT_HOST: ENC[AES256_GCM,data:upO8GzgtXGl0,iv:u/Sboj9tS79P2ibVNANZ9ozniMqvXXl3McyDDmyUGr8=,tag:3lgW1q2C3BhK2U9quVpaKA==,type:str]
  SECRET_NETWORK_BGP_ASN: ENC[AES256_GCM,data:Sc9x/Qc=,iv:facU3gZl/50uHBjzO39Nckb0VGjFyrf65bpN1Mgvf6E=,tag:5iJTrnNtOIOk12yLRFnciQ==,type:str]
  SECRET_NETWORK_BGP_PEER: ENC[AES256_GCM,data:SIq5kyG3TFXS,iv:ki7O00Xw/0WLK1a3JvkmtS0qtNTKcW947kCKI5fSMsI=,tag:Q4WAFLpRU6Iw8DuPQRl8LA==,type:str]
  SECRET_NETWORK_BGP_PEER_ASN: ENC[AES256_GCM,data:Skpf/7M=,iv:PS1OLdY4+8vjhre/0dRmgLqkBVXYCmYxDNJw/HC3xPY=,tag:bqbkwSx9URvR1lkn5tapvg==,type:str]
  SECRET_NETWORK_BGP_POOL: ENC[AES256_GCM,data:qdSKLr4qjM30Tne1t02z,iv:C0S7+zrlZGWje5gWqcfs+6XmE35tfAiEsnbXhnX3H1c=,tag:NgMCl07+HPx28q4gyNAItw==,type:str]
  SECRET_OAUTH_EMAIL0: ENC[AES256_GCM,data:0wz9XmDD1pB3W6XJ1zUBNEo1tn5I,iv:/djHfb03GTqKunzque4pTKnCbt39Eq4Bhb/ikJWKgpY=,tag:C6ZuKe1srA8MujxDTngJYQ==,type:str]
  SECRET_OAUTH_EMAIL1: ENC[AES256_GCM,data:KtfqXVguF3ViLIQU9dEeYxwHlg==,iv:aZsqBPW5WuXtwjTtkKT8t5dLxuBGSepLLcIZJFuU2fI=,tag:lOzf6CEawZwdLcwOsCkeuQ==,type:str]
  SECRET_OAUTH_EMAIL2: ENC[AES256_GCM,data:kwWOpq3sYacpuvmbY1UfCZDmpEv3UT6iTuRv9w==,iv:f5yT1SL6LIxBY/6MriR5riEUvpPfzqMcPl+aogtyiag=,tag:HrqzcC+TT8h+Kqs+HeZ3Xg==,type:str]
  SECRET_NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:YS+a/yge,iv:Fm1qbugRTyJzSzd5ZYJf//vpN58Z5PDOQtfMpYhSFpg=,tag:PI69qIg4Tv0z3piOLM8w7A==,type:str]
  SECRET_NEXTCLOUD_DEFAULT_PW: ENC[AES256_GCM,data:LNVl/VwHr8FqOtTjhIgSFjSKnw==,iv:jxYjuFNDf5h/FpZKJLeSA1MMqOcTYAuKWiLlQ5i/C0c=,tag:V597r+yc6+T1vYtrp4gMPg==,type:str]
  SECRET_NEXTCLOUD_FROM_EMAIL: ENC[AES256_GCM,data:MJzWrRWz4KWCC7xu2YXLcOt2ov0=,iv:nLPNp6+9MJCazUGbWLuUPYF4Ud4IXVuTyBaZLCBCAM4=,tag:Pbd0B1YKzDhiZ8nhkMdpRQ==,type:str]
  SECRET_NEXTCLOUD_FROM_EMAIL_PW: ENC[AES256_GCM,data:J2U9nrjEIm+ludAutwdp/w==,iv:LCNbyudPgY+XmfjrIkJA1XS151qEhejTYeCKzYxpIdc=,tag:71eIbFbcjKO9vZuJMwMAKg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQ3ZjamtZa2Jjakc5RFV4
        N3phYWgxUlQ0K0J4SmNlSEdycFNHemF5U3dBClFWWUhYUzRnaG9UYVZpUHZQbWY4
        QllLb2h5Qllyd3RMRjJIR0VNWEtENFUKLS0tIEpESGxGOG92SmF3Mm9VNXJMenlj
        SkJ6ditTZ0IyRm84cWtiMnVuZ1BlL1EKT7Rbvp2udmG4/ebBZwTdSYrH5V12R4u9
        bdm0Hx9h1ifDd2IAZa+duEoVGQI+2/dmc1Lo0uMI8YraXNgDQBDrVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2023-01-08T22:33:28Z'
  mac: ENC[AES256_GCM,data:N1+gToK177kpYOV24KqCSVT1++F0PxepDxuMH9TGoYtFSvDBgUVlL+N5sxEi7htYpNEygPB4jFCGqzQ+fDNZjSN6g736Ul0iIFTohM2QrR72IuBspva5MOlxX220w0xnP33vhqwMCmQ1bjFM8IPNjOdp9BCNodaNFXh0lhlefmg=,iv:Z2c+5gDBIjIFIY/WT7gOcntagmkxQeWRoBxTwxZ+i1A=,tag:itkue3wjf98xjOM/ZICL4Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
