# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-blookums
    namespace: flux-system
stringData:
    SECRET_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Zwy+GJO+yBe+z1IRxyjsBYjtK/4=,iv:gandu9wRmIzhhIDv+qdGurbbR2UruCvVHfL56Tdt9oc=,tag:8DLEZa42016SnBpRXbC9Ww==,type:str]
    SECRET_AWS_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:j5KwueWMlRIK11QLiPNMvqOT0Yx+F2qiqIgvlwFZl9f9E4sLQ8gR1A==,iv:dlq2Ki5af6pzFheN/0I1oA/TyGr2HRDBXlFyLQncybs=,tag:JV/2Qrr7DEB8yeYJNW9Adw==,type:str]
    SECRET_AWS_BUCKET_NAME: ENC[AES256_GCM,data:3bXRqJdBVvK4B3s9j5F4H4g=,iv:xwT1YHJyFuVl8WaGTW31AyYkXfMgv+U9ZjLWCPOJED8=,tag:rr/ckKLNC2ckqW+f9OC5Hg==,type:str]
    SECRET_AWS_REGION: ENC[AES256_GCM,data:LGkzZmlpO/Bo,iv:xhlqgLyKeE2FSMKiNvm85665H/iZn+y8/nf48m4MrvY=,tag:/D+feCTLjZpF0Eotnu0IPg==,type:str]
    SECRET_AUTH_URL: ENC[AES256_GCM,data:SqnxzvqBawncIdgW9fdOUpX09kyixQWWdBCqEsdvH0lG6hD5T1wamQ==,iv:JvIjzj6/6A7q0J8H6hK1pHF7wJkmLPzNQgTMkXQNEwA=,tag:xBAk416izWG+KIbIE2+aiA==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:dN4YUUzuWURTWY1tHiFaTgT8BLkUFyx1kZdSnZbugGholU/v1xGbvL8vcjjW67GpGbYkOGAy4d73MKlQWehU78bKO8rj5UZbbKzigPLEnN0bn1AIM/dApj668aAvsYnpAqVGmg2gVoPP1Aku4WZE2vbXQw8S7VVJnA==,iv:Lew2WjLR5ninvUhYqitjSsVmbl5NvYkgye1OEw1tQAU=,tag:B7/i1/mLF9CEtNKJdkEU2g==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:3TZoYmHrVzwfWxweNNnzTSdxjg==,iv:eM5wmB9HwU8DrGVZRE7ssQGM/IwMQ7UXMDN84eVsEIc=,tag:olDkY38QVKofeWL8sUOVGQ==,type:str]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:u/sklzOneToiccCkLG4wlWDiZw==,iv:Rfu1ntiPFeUQoZSg7kyYYi7cAl7QODdXN0FdUMVvlJQ=,tag:Sb64++ylc3UWzFXAGhY7tg==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:+ANP18jRlhTeTrsRp4BnT8xzzh+XOBT6jKTQ4heGEyA84V/0MySEF0lSCMxjaLL8VltmWHz/9ZAHNmUBqK+F2uwGdYXl9bXV,iv:kJU3Gzd5jzj5s7rotNaetvyKJoLNLyKeQitz6DjozNU=,tag:VCgrx+iY1r/qm/y8gXyL+A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:h4GySD4GnUZj3i8eg/Y=,iv:sQmETmf9PsvwoCVLtHc5sz1PRUVY/Ghb/611SBb3rs8=,tag:qFWNp63SORlt/KPXnSawUw==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:EXpD4Cyuk0/Bbd0p00VdwICt4i/u,iv:tgnP5mSkWZ/HXnWGTW3TmOR9x7aJEQol1azLFmoCyME=,tag:jiVq0Lf2QoM0x2mDM7LtLQ==,type:str]
    SECRET_FILESERV_IP: ENC[AES256_GCM,data:XeG03TuILgAx,iv:GpB/FHO6T/5d5Vxx+sTKWPx+fOuSIn6MY+PyaEXh3Y8=,tag:/QYa/23uqh21tWk+g7NRfw==,type:str]
    SECRET_FILESERV_MOVIE_PATH: ENC[AES256_GCM,data:VqKpJPMRcd9sSvUX1I+PgBADqger1ttto528fARYZcZ+IAo=,iv:0BD05mPpRGMPp+TAvmtla7sdSn5OB2nIJ9VC4Hg19KE=,tag:d2i4nFzjxk5B0sLwaTUwJw==,type:str]
    SECRET_FILESERV_TV_PATH: ENC[AES256_GCM,data:DZQuD3r5eCVuXtMMAuC9I5++s7GEyynKGwwX7xUN0A==,iv:6A5RzYZCRlFgZVEzRG8KTxBUN8aWR3zQNbh1WIcAUQI=,tag:0X33NzXOfbp9+nM/1saSdg==,type:str]
    SECRET_FILESERV_INCOMING_PATH: ENC[AES256_GCM,data:wKCsKfXUTp+q74xY924Zed1DWGByp+TTVuHWjBd6hjZNX1bV/w==,iv:SYefqmpZgaxud1ZXDgJGA2eQ85GbnD0LLxoU+oN1OLQ=,tag:dLlq8hbiLcmuCzJamjmBkg==,type:str]
    SECRET_FILESERV_INCOMING_MP3_PATH: ENC[AES256_GCM,data:jhBcWblIrV8zUBFkIwVSiYR5PE2ZUWXk6jHBHtT7ATo=,iv:bHHeXKkXvlUCSHLVKYVj7WCPx2L74LRNRwN3G53yBIw=,tag:gHPinYhu8aKNuAHxW7ZN8A==,type:str]
    SECRET_FILESERV_INCOMING_MOVIE_PATH: ENC[AES256_GCM,data:5NlOPkWmQPPIZVgU5p0foNGkVyH5oCQiLuUvHYE5l61Vlmbpb0FvuL4l10U=,iv:Oi7439iRznoiCWQhO19ffqCGNDbLTaZ0OO8wrOJYDdM=,tag:qNeRJIUhWteMuaKhSTaaug==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:s+WBfw0f+JfZ8ckPyZ1JNRAw6iA=,iv:72rmU1WxaEGWWTBNzWF1/2u73HOJX42CGOZowEbrQuI=,tag:J7UMtOp401ZVKsVfoxrr9A==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:wghMRCcdq7M=,iv:EFb4yPH8lotBeW2OZpnm7W39rPlybQ4ocJdWudGw4QU=,tag:VuzMlHcmLNSPW6m64BpubA==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:s0BL6sTo,iv:xtuHbwVUBraStwAixE7X+AiGMw7jZxKOUJHZOwBqwDg=,tag:iME/DhCTqVqSckA/UeU8VA==,type:str]
    SECRET_MQTT_HOST: ENC[AES256_GCM,data:cOruNnaXFhL5,iv:IUXi6goGDUpMJCP41pBouID9EyHjSmasgZoqwFeXK6s=,tag:A36XC+Q+mqf+8lydiIECAg==,type:str]
    SECRET_NETWORK_BGP_ASN: ENC[AES256_GCM,data:WNlopOA=,iv:3A9tkdEvSAm0UNhj6/7+D3O9qZNLZnlLHKZ5iHA7iO8=,tag:YUfDS6NxugmRUTjo2TNmtg==,type:str]
    SECRET_NETWORK_BGP_PEER: ENC[AES256_GCM,data:G63TGRFrwldE,iv:lQuNU03aV9+qcU/lrIfevaVJ8toC9b0HVCiUv0HLLsM=,tag:k/tXUsl+hjFjSocz6Bzt0w==,type:str]
    SECRET_NETWORK_BGP_PEER_ASN: ENC[AES256_GCM,data:KSpvvfk=,iv:q2og7o74nwYooqlXXdUmq3Z87ia/E9PbltLWayf7rPo=,tag:7n5T23SgFGwyuVnDw72AFw==,type:str]
    SECRET_NETWORK_BGP_POOL: ENC[AES256_GCM,data:TrTBe3VKvY+29gO3f25K,iv:DhN/X77ZT+Ai1lFAfWI7FOcl6L0O0PyR95P5PkXosmQ=,tag:UIxaKyzJgkP5KDsRhdvlgQ==,type:str]
    SECRET_OAUTH_EMAIL0: ENC[AES256_GCM,data:2a5DZdSIhp9nGD2WFMXBJNlr9cbm,iv:xZRtOzS+dUek0xaS2gVIeV/fWf4/o7GhlCL3sa2Xdt8=,tag:Zu2jyPMzyrLinLddy8IvLw==,type:str]
    SECRET_OAUTH_EMAIL1: ENC[AES256_GCM,data:Jch1mVqYaBQplUKLYSPIXKoPww==,iv:fa8Tn2eUosJxuq7IXTheqqHQnE5ugU/LggHbSzj2GnA=,tag:sW6c/kVlj+Vi4uokePkTzg==,type:str]
    SECRET_OAUTH_EMAIL2: ENC[AES256_GCM,data:HaWqxJ2CTEaSC89hkG3JVDNvybp4UuDA2okduA==,iv:IF8+Cai8cBuYVdADQwZ7Tty9I6JJ34sNeCugX/wW7Vc=,tag:FoLGHJ2kAt/MYcN7t64DLA==,type:str]
    SECRET_NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:mV1HItcQ,iv:OsSg49ZN6qcDgXzDE2U54+8WirBeiQz8T1lekZzaHz4=,tag:S1Fl1j3FMniKy9rOHv6KrA==,type:str]
    SECRET_NEXTCLOUD_DEFAULT_PW: ENC[AES256_GCM,data:PFIbbvhKBuF1M8h+//30JR/O1w==,iv:5q+MxPqAI9WB6WUB6+Ft6cuJ77oXVuTEzor2aa7ECA4=,tag:40OYhomS8yqIEV8np+OwcQ==,type:str]
    SECRET_NEXTCLOUD_FROM_EMAIL: ENC[AES256_GCM,data:rAfzBUFPUF8yy80D5XjOSiIAPSs=,iv:t7mUtaQKrJ8Jdi2mx7yZVyuvyAILegBFI+qEx+XFBN0=,tag:j5WXnmQI9F6x0xQ+Faajww==,type:str]
    SECRET_NEXTCLOUD_FROM_EMAIL_PW: ENC[AES256_GCM,data:8huzYxbHhAP1EIQ5ikPwOQ==,iv:K9Tp0lbbBlcyMJwM9WA/fZDMLXsXvCwxcg4ASp1FEPM=,tag:hl6MrFjTS5Fonit/phB1Ow==,type:str]
    SECRET_LAT: ENC[AES256_GCM,data:59FtGkehzzJo,iv:rJuyLKblE5TFYg92jtSylRLOPqbnOjgeL2TCZ3fDLa0=,tag:DUAvzwsyNQIXP9lX7t8K+A==,type:str]
    SECRET_LONG: ENC[AES256_GCM,data:4l/PtCAByByb2Q==,iv:2JoafwtPd+wnGoCdO+tezoPI1bSXNcnSY4pLh8rKg68=,tag:dBnzKV2NS01NWBy7IZJBvA==,type:str]
    SECRET_ALTITUDE: ENC[AES256_GCM,data:nuWo,iv:zey131v3cy4w3+OzRDjt+UaSk5Etyo2/UCQwrQ6+KuI=,tag:KHuBMGIHjjxaDbd5qoVq6Q==,type:str]
    SECRET_DOCKER_REPO: ENC[AES256_GCM,data:KFECBRt3bTPpVjTET0o=,iv:ZyZDY2ryrHjZN6DQOF+GQrzUPaZ5DL56L3S/ZE5TOrQ=,tag:WbDuNo8BmfVBlwxGfcdYvw==,type:str]
    SECRET_GATE_MYSQL_PW: ENC[AES256_GCM,data:Zr9fZyhlOc5lmXYezUlUfw==,iv:eqBgT6de8Hz3riHOacsQ2Z2/F46d4jmZjYCL6WV5HWA=,tag:CVQUT7sUTtXIAtdyb+GSrA==,type:str]
    SECRET_GATE_RABBITMQ_PW: ENC[AES256_GCM,data:TxKeMewO3LdaXw==,iv:l6ltgjrHS/dVH5XczZEtBX2d6eaxVqTChNnqHsQHwXo=,tag:Q1e3gDwQkoFuPr87GG3pcw==,type:str]
    SECRET_GATE_RABBITMQ_ERLANG_COOKIE: ENC[AES256_GCM,data:sbhsAYBS68WepAGXfGVYDmSi0plWuygc6r9Rrf/Akv4=,iv:PDffdv/CtX8mmk1fQ2JHSEJ7DZHKFJM4+2nshLhzT2Q=,tag:CK79GX/uCUl9PdGEoFrN3A==,type:str]
    SECRET_FILESERV_GATE_PATH: ENC[AES256_GCM,data:KzBqKTJLuX00oHmrXQvSGpzrEqby6lqPWgL9Xdc=,iv:+V8i1HgJbSg/qw7kCxfZ3cMvSW0dg9XG+8+Vg9m7CLk=,tag:Dq2ebmxUdvSo/f+prdb6dw==,type:str]
    SECRET_FILESERV_SECURITY_CAMERA_PATH: ENC[AES256_GCM,data:b5d9ZyncdHatyrIJDdMkAS+Lzj88w4oB5lKJaqA=,iv:aYu1oBIAqrxxuV/pI0+LmJKP6Kph9UsIH2BGaeRU1zM=,tag:wBD8jkCl2h1l/T6cn9LFAg==,type:str]
    SECRET_FILESERV_GATE_MYSQL_PATH: ENC[AES256_GCM,data:q0Nox2nN1FjoEsatIotIPNA7AT3KrxvhuYY23gqQ,iv:rIbOYCD0cNP2PdUvl/tYYx0qy0MEqNI3lBQGn9LwaBY=,tag:RHpBHfMQmJvUiG+ZXOo04w==,type:str]
    SECRET_DOCKER_USER: ENC[AES256_GCM,data:BVRaOWGX,iv:SsJvWag6qwWUImMzn9tvnW+QyKaD5QEs6CubOpalx/s=,tag:TTisem2yy6N9uHGxH4IztQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWGpJY0VhMDJubEhvZ1BQ
            UUhiRFU3WW1XeFJGNFo1SnA2TEZ2RkJjajFJCnVmT1B2VzUydm05QVM5R0EwN0Ja
            NXFyM3FJZS9tN0xGTFpLU05tWE02Q3cKLS0tIDNTbkxpaXA0MUdOSDdvekw5aUFa
            ZFlGa0NISjBqeFJiV244RXBqSlkwL00KGFGLM2MIGXSr6E9RHkQRVkH4GK6xSrNl
            lKp4UZsxbKWvYOsVc20pcGmgKlRfV0dxpFK/J9eQNtJxCZeDqc9wRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-11T08:16:21Z"
    mac: ENC[AES256_GCM,data:+wvtGhlExs5UVY19IB+DT6QJj3oKuTreWjxlveTgG+FG5Z5I+VAcUKVgf8+eEyy1jND3RAFMYFs1cD3/bchlPJfMxW8xsOL8yRJsVfDPzZeSXaNOT43KPab70w+sIg44M4zwslwL4BA1UVNBrMWH0fZ8srhYukWa9hHdzgsXymw=,iv:cjATY8QBuQomrwJBy/Q4xnkoqfbTCPXXfamOIon2ty0=,tag:mrCPOD+MNij2Ug9ng4JbUw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
