# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-blookums
    namespace: flux-system
stringData:
    SECRET_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VToshniGQYFnj2IL9OGDei8PJ6w=,iv:cOLkP5imdvsJzs4bKGuZMPGBeVznjra4OTj/nA+yN9g=,tag:5Am3U0cIUE8Zcm6uHi9FDg==,type:str]
    SECRET_AWS_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:4ubcBkIv8BQv8T7RlZyWegz0ToYpQ3Oll8qI7BM+9J03Kv9+F2K0pg==,iv:PRGsgNCQ4h100Aew/8Pqz6skrJ/yOFsy1LdLKXs0XKg=,tag:X6O3UwKyX27aYAPTm/SxXA==,type:str]
    SECRET_AWS_BUCKET_NAME: ENC[AES256_GCM,data:t0qKrM70/IuDQPhJCbvCW6I=,iv:YJtcc+8v6rL2IQCpso71t8GrlWBkT3gEdWBSMP0blO8=,tag:LrD0yVqVMkn2DWIBbA2SBA==,type:str]
    SECRET_AWS_REGION: ENC[AES256_GCM,data:MiDp5BpbByph,iv:usl8mbYn/EKqahcgYt4t45NM/osJI1qnoyvKEf9zLhg=,tag:TbBDkqGACoMLDEQd81O8Jw==,type:str]
    SECRET_AUTH_URL: ENC[AES256_GCM,data:P+Vs5tvCDJjA5vU3KwMFLH9Yu8QDuIyGkRdNM20fkCHXCTczAv+yzg==,iv:si7wdw15r8jrHbJGPXjqFQmVVq2sNjAlnJI5K0b3eqw=,tag:01L093+OlRDtDR5O81vAog==,type:str]
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ENC[AES256_GCM,data:qCFpzogSxoGtf8RqiuE4LXENCGWaiqLH5arfw8GO3K5lkXUXCyB8LpGdNkC1aKbkyLktL3YM52jpC/SGNDYkHuMiq8P46ERc1b8ty6gUwb1DCUTxH55Bo1KhoZA0HA9annnZgbJgQnq29DLVQjlc6eTenWA71H8TMw==,iv:YvNnkSOiHikqfS6wd7Qds2ty23enfC51jYviKzkuU5A=,tag:rBeQZI5wVlA8jbFbMK1jSw==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:NgEpEJ1xVDuQhF0hc4IFbG9vUw==,iv:74VVEU3+DtHeyM8Ci42hREvfUF3yQP6G+utuxoAsoB4=,tag:fVkX1PEw/m7LAXOFFNd+3w==,type:str]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:8FzC5turjfA5LhBS+9xTkzA9aQ==,iv:DXvQGVzzpxjcglv7G8PC01ou/Ifn/hwYy+5EPusJqVY=,tag:+70bPeHrhsMeLYemVSpbBQ==,type:str]
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:N50KbmvVsJtTfrBGTFScYPhjZL2Y1f7Fws4/+HKKDGDunw446SFVFT9MGP1+roLq7D8Aww+LM0GF+897n7NHASrAq/w3ueIv,iv:K7T0KVyH3k27fgG5ZEyiQ9HN4Gd7asnP5CR+5r7nncM=,tag:fdY26pyUAWhHkU/evd+mpg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:UFbiWvxXAJqU89+F0Pc=,iv:wqFUYGJI64Rd+UqF1agaPjz4o0VT2ukOAKzGwiKCCP8=,tag:WgpMI1bHAjidAwZ9HTpBng==,type:str]
    SECRET_EMAIL: ENC[AES256_GCM,data:MVVV+VP8VskkL48h2bkQe1uFT6Tm,iv:8qvO1HZ+KnuTh90NKkeqhJ42XGq0pP6ShrTjBvEjY54=,tag:0rI56zxsBFrj4Jlu3mK7iw==,type:str]
    SECRET_FILESERV_IP: ENC[AES256_GCM,data:SWwuRnlXMQc6,iv:dRbVyjoz7qS66SWwG0sQLv5xY3qzQLmwpS60IqPj65w=,tag:ko8Zm0GkxSW7D2i47yr7uQ==,type:str]
    SECRET_FILESERV_MOVIE_PATH: ENC[AES256_GCM,data:+L+pTWz6+Fesnt8KqsI+LRM/e0kLFQ1lN+U888MZF+Ee/d8=,iv:j/b08uy/mal+VD9wGZmlUHjZr54XeviI1RcKi2RgbZo=,tag:zjwk5vJuDF/XBIJEypHBWQ==,type:str]
    SECRET_FILESERV_TV_PATH: ENC[AES256_GCM,data:Y1vVEKXX5gQvmudSfBIJ7SfUixh2hQpiWdyk3VjiZw==,iv:qn82ajFtWp5sVgcZVKEzbqFwP8iejvb2LAyhXyFPcdg=,tag:maoZ/35CPn4XG9XeFXWOwA==,type:str]
    SECRET_FILESERV_INCOMING_PATH: ENC[AES256_GCM,data:DlCTSAaBEXmN/W3reqD+7v67NTdzlGRzWmDNDp+qVdUNogPimw==,iv:GUf6S4wYJdKf2GvYNHJZWp7BRXljMkJoNLDR/bd4eLg=,tag:iZ9JniiBbelaZ8mzp8l2hA==,type:str]
    SECRET_FILESERV_INCOMING_MP3_PATH: ENC[AES256_GCM,data:dLQ8QTgVlf50f3d1nHiae/FFfObR/y/rVaL+NMpOa08=,iv:lAcVmxuzolSMwGPCfmbB/r7rhyWCNbVY/YceB+0DRs4=,tag:jlm0YeFNe1SMUBwd/Q5wDw==,type:str]
    SECRET_FILESERV_INCOMING_MOVIE_PATH: ENC[AES256_GCM,data:talk6eB+U/LKCJJ5P/7rBC91qP0+MrNgPIE0D9IX9yBjUK0hF6xNOA+3nHQ=,iv:Snk4ckwVcsYTRpqB2YdIUT5DoZx2pKRoVTXIniFk3f0=,tag:TTWw44VmfM0HyWWQv6DvyQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:oj1TErw4/GsMVPut9+DxcbgTU+A=,iv:wH4MV0UvAl4HGwPaPX+N89MrH1IZabWih+r09+opUFg=,tag:Vvn4Gv+kWt65UlI5IVsROA==,type:str]
    SECRET_MQTT_PASSWORD: ENC[AES256_GCM,data:6wsguJ8ffB4=,iv:CXlr1XwtmnLgb12A2yYYNKie+AFo7Ii0ZhiEAEs9Tvc=,tag:xGzX8Kd2WQM6seoYR7HEYw==,type:str]
    SECRET_MQTT_USERNAME: ENC[AES256_GCM,data:rIG1wGIn,iv:HhBPRtd32nlug+7pO0JveJ10HZcZrTbKznacRsEnvy4=,tag:GRw+MHrwUQE/tzO3txCsKA==,type:str]
    SECRET_MQTT_HOST: ENC[AES256_GCM,data:eHSEwTEt6BeJ,iv:5xR6cuzuaAwjhhitx30jhvDN/eJTVieZyM0srBSBWZE=,tag:HqBz9NZk/1y9JzyS+ykBoA==,type:str]
    SECRET_NETWORK_BGP_ASN: ENC[AES256_GCM,data:0VK5FhA=,iv:6EuE3jbSt2XC9651hZqjwgChHRvtyp/9GZLI+pStSKM=,tag:1NBmUOBcxAvcm/lK1eNo3A==,type:str]
    SECRET_NETWORK_BGP_PEER: ENC[AES256_GCM,data:FCvjP/j562TM,iv:Bq4BG0DN10Ztakr1ZNDdEMrBgRKbKamQXPxevEgTLhE=,tag:BWottMASTJYnucNr3Dv/1g==,type:str]
    SECRET_NETWORK_BGP_PEER_ASN: ENC[AES256_GCM,data:PqBLI2k=,iv:TI5/sZIc59pY+hr6a7FQ4hOI9PSeBNo/a26BhMEKPRg=,tag:DUGLQz4LFSDBrVTT9oXOpw==,type:str]
    SECRET_NETWORK_BGP_POOL: ENC[AES256_GCM,data:135hrdsw4Gxqy87I1RaU,iv:krykjTBaBql/6EhAasXW6/+XbzRZ+YGBYHrBzfuIQsI=,tag:Ewp4/HvDwM/QQS4FcD6XuA==,type:str]
    SECRET_OAUTH_EMAIL0: ENC[AES256_GCM,data:KpiWiNYIMZ4mR69+ajWWoErnAUe6,iv:RKnqxS7FTil6BMNRqcBLv3bQJXGaHO2YRYEN7sRvdwo=,tag:LODJBruKi+3Y06/wK0Q61A==,type:str]
    SECRET_OAUTH_EMAIL1: ENC[AES256_GCM,data:qMlH66E4fUcsx+8tCWz/D5MNHw==,iv:9LiiQdsj0XRJJZLvzuyKyE88sBw3weiqbhrkiVLP+3k=,tag:Pr7HVjylXMhlNqqALc/How==,type:str]
    SECRET_OAUTH_EMAIL2: ENC[AES256_GCM,data:/xU9Exl7AzoWRqfvUkzJZAJSGFq4La6NQ8FHgA==,iv:mIodwktM1rpPA4AvnkJCe2IHdaQGp4wBcqDxtpS/mXo=,tag:AMlnrNJYjfJ+TRFAQfKC+Q==,type:str]
    SECRET_NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:tzWzWLe9,iv:CLmzsTsMz0bUZqVO9ejpKXf4MXvgtAFTmtGoRi6ar+4=,tag:I82oB3r+MOdvXrFaaEikKw==,type:str]
    SECRET_NEXTCLOUD_DEFAULT_PW: ENC[AES256_GCM,data:zPMQA5VZTsdCyaWA2OTWVaSMAg==,iv:sq4DDydl/Kita7iHz5vKkGiQ09YHigGRdd8GWViZ1/o=,tag:pqeuOMqlzNCqkLpMYewWag==,type:str]
    SECRET_NEXTCLOUD_FROM_EMAIL: ENC[AES256_GCM,data:pGrxwfiFrFuVQaf3t30Uh/MBoM8=,iv:v3wb578p2IOpMafYiHOP66or1CfnYsZCNQQHRpas90o=,tag:NEtnYkDIDOc5VjFV4mm1tg==,type:str]
    SECRET_NEXTCLOUD_FROM_EMAIL_PW: ENC[AES256_GCM,data:cKy8UWkRJA6sTD/cvqiWEw==,iv:iGGgg8Iy45jolYq1HarxOQhsg9vW0LX7ayuIrQOETdU=,tag:esaEA8rk1L5BPkQgSwlkxw==,type:str]
    SECRET_LAT: ENC[AES256_GCM,data:6HnBBReXaso9,iv:mAP8jowbURYzz7pvJriykne3NFEeXLbxtaPUiPx9maw=,tag:KolDewtYnVWGMjItJn4cww==,type:str]
    SECRET_LONG: ENC[AES256_GCM,data:oxB2T23U3xqOGw==,iv:TVpLbEZhzgPis6tM7dSO+6ikwlSRSRssUC1NKYDf8iM=,tag:K//TJJ4g99ElHsgSNrg/9w==,type:str]
    SECRET_ALTITUDE: ENC[AES256_GCM,data:4jAN,iv:1cVi6l/CMV81XkcP7m4beO3N1PHwONGGQtkyTlQ+Gq4=,tag:STMUcghIJTGFxtYnQXj4/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZWUgyczZ0TFAzRXEwaEo1
            MjdkTmEveC9hRnViYlhpQWlMenRNNGZValIwCnZNWEFjVWsvMnRZejlMZFhxODVX
            dnFHRWFYNlgwQ2dGeGRHYUpyZjRtT3MKLS0tIE0wSWNFRzJYaVl1UnJmdHFmdzIx
            YWl2Wmd5QkIxbzB4R05SS216aVFKV00KC6JlJRL4Nsuv2MPnPTZ6KChk7Tye+UGZ
            8754rF2EFA6JFgNLJeG6pLdgt0WqPdsOfj2/EHoca4OFOa9jJ3XReQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-09T00:22:59Z"
    mac: ENC[AES256_GCM,data:qz0HRxwqrOJ09wYzDN4Gowd7nZny20GakWMGyB0CvS80irIs1w9loARybcOa8nWGrMEHbmKDJ0hIcKHkr9YIyO6mFYE/WhiM6OkwEo2P6+FEQ4qGCTWxjBmAoMT5eg9sPEPUZt+md3dwVRulWzXCwV8TRt+JWTAKs2vjNEjViug=,iv:eRdFG2MsdcG9cJNQ5VHy4bk7VtRYC1RUwFD7deUZeds=,tag:xNQ5TegXP5/RtW/KdAixjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
