---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 10m
  chart:
    spec:
      chart: zwavejs2mqtt
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 8.25.0@sha256:9ffc96bc08322e0d7c88e96c8342d54dd201535a5b26f0b0dd8681e62f552660
      pullPolicy: IfNotPresent

    service:
      main:
        ports:
          http:
            port: 8091
        type: LoadBalancer
        externalTrafficPolicy: Local
    env:
      TZ: America/New_York
      # -- Zwave Network key
      NETWORK_KEY:
    securityContext:
      privileged: true

    persistence:
      config:
        enabled: true
        storageClass: ceph-hdd
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00
        hostPathType: CharDevice

    podAnnotations:
      backup.velero.io/backup-volumes: config

    nodeSelector:
      aeotec.feature.node.kubernetes.io/zwave: 'true'
