---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zwavejs2mqtt
  namespace: home
spec:
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: zwavejs2mqtt
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: zwavejs/zwavejs2mqtt
      tag: 8.6.2
      pullPolicy: IfNotPresent

    service:
      main:
        ports:
          http:
            port: 8091
        type: LoadBalancer
        externalTrafficPolicy: Local
    env:
      TZ: America/New_York
      # -- Zwave Network key
      NETWORK_KEY:
    securityContext:
      privileged: true

    persistence:
      config:
        enabled: true
        storageClass: ceph-hdd
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-0658_0200-if00

    podAnnotations:
      backup.velero.io/backup-volumes: config

    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: app
                  operator: In
                  values:
                    - zwave-controller
