---
# yaml-language-server: $schema=https://kubernetes-schemas.zinn.ca/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-postgresql
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: postgresql
      version: 12.6.0
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 5m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: docker.io/bitnami/postgresql
      tag: 15.3.0-debian-11-r17
    global:
      postgresql:
        auth:
          username: $(DB_USERNAME)
          database: $(DB_DATABASE_NAME)
          password: $(DB_PASSWORD)
      primary:
        persistence:
          storageClass: ceph-ssd-xfs
      readReplicas:
        persistence:
          storageClass: ceph-ssd-xfs
