---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: valheim
  namespace: gaming
spec:
  releaseName: valheim-server-charts
  interval: 10m
  chart:
    spec:
      chart: .
      sourceRef:
        kind: GitRepository
        name: grownseed
        namespace: flux-system
  values:
    # Valheim image version
    # ref: https://github.com/lloesche/valheim-server-docker
    image: lloesche/valheim-server
    imageTag: latest

    replicaCount: 1

    # Configure resource requests and limits
    # ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 1Gi
        cpu: 1000m

    valheimServer:
      serverName: Blookums Valheim
      serverPort: 2456
      worldName: Blookums
      serverPass: ${SECRET_VALHEIM_BLOOKUMS_PW}
      serverPublic: 1
      updateInterval: 10800 # every 3 hours
      backupsInterval: 43200 # every 12 hours
      backupsDirectory: /config/backups
      backupsMaxAge: 3 # 3 days
      serviceType: LoadBalancer
      restartCron: 0 5 * * *
      updateCron: '*/15 * * * *'
      timezone: America/New_York

    persistence:
      config:
        enabled: true
        size: 10Gi
        storageClassName: ceph-ssd

    podAnnotations:
      backup.velero.io/backup-volumes: config
