---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: movies
spec:
  storageClassName: ""
  claimRef:
    name: movies
    namespace: media
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_MOVIE_PATH}
    server: ${SECRET_FILESERV_IP}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: movies
  namespace: media
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
