---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tv
spec:
  storageClassName: ''
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    path: ${SECRET_FILESERV_TV_PATH}
    server: ${SECRET_FILESERV_IP}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tv
  namespace: media
spec:
  storageClassName: ''
  volumeName: tv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
