---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: metallb
      version: 0.13.10
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  values:
    prometheusRule:
      enabled: true
    controller:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      image:
        repository: quay.io/metallb/controller
        tag: v0.13.10
    speaker:
      metrics:
        enabled: true
        serviceMonitor:
          enabled: true
      image:
        repository: quay.io/metallb/speaker
        tag: v0.13.10
