---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-url
  namespace: flux-system
stringData:
  address: ENC[AES256_GCM,data:GG0SIBJ1HZVyaMekrzHLscl9Sh5T/SZF08yC2R2VMRbgjP2YBlO8lX9AB/UsyD20jmp5/Y7MZgyTnDbfcmbRPxN9XnlT3NTK11/nJNt+v/9uXy68DJHf3yMunhw01Y+mFiiwclJtrBr6EcgzMBaXtVYpxSjMZ3Q+VszQHYWeHfH+uunW8KkA0ZPPASEnF4ebAWFaqBU1NyYI0rtOOP8uCc+hy/o=,iv:1YVgasxdNVZqD2ajuNQaml347c4S3fIRGYBGYN19wJc=,tag:+tMlxzPFTsd1D5U861skqg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5c1poZkRiTm11c2pUSEl2
        YVVPbTlmd3lWNDJzTHBpSW15WHp3RnpXQ24wCmRPdDloZXVYVVd2L0RGMlBncHl3
        WFZhQXRwYXd4czkrR2lrb3dqMzF1Uk0KLS0tIFNpZ0RJTTduS2h1TXNVTytpczA2
        b0UrRktIek8yVEZnTjRJMUIzT040VkEKPXMtkuiaqZmHpYsfSHOCFOjWdqSvOTCV
        2hp2jJTJNEtJSScS8T4g139hx8uaJ2sHwz3aq9vDXNS6i+9cqpnnVw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-12-04T01:45:27Z'
  mac: ENC[AES256_GCM,data:XtBcPQdxvApXpVkbNpnrGnpYelxanwDj+YpR610ZBPA5pk3I0wLdfpP1exfFcsgFM1i+/QjbevexEMktreHTPpW8Z6UHWUrTeZQx75U/xHzbpJEcKdbIl42vsRs+HRpR2sf7T56qG/VK5IVNMLXwITDAl0WyUygIetPJz+g8J/c=,iv:UK8gcxt+Qf10j/frioa6JLkjWHVjVmWhGt/H334FoPM=,tag:4JwhjykpHnCvks/IMOXd9Q==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
