---
# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-url
  namespace: flux-system
stringData:
  address: ENC[AES256_GCM,data:HMSZHdPXJifZjKQzEplr9rpCc5oD1fjU7ADNJ0Y3QIV8KJBcslfP9UCKRZFsl8ORJDL4ELy1Jt0F4tf8m+l67nO2W5SW/aG3kFFxfQbq9Zq1HHD1PXwZVHUec+11Io8gsLiC3B7iDMKoLNyc6OZ0pQyviLPWT3KteQ==,iv:iaooW/OHxVo5mVS4OZa0qCf10Z9kqPx2QhfO8cXf2Os=,tag:QVAZQ86ohF53flJm1q9sWg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1p6t9tehpxgph8dac6lvaahcn6tu9epejj42rmwm49azl942p2eys0zjlr7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMODNpN0s0SWw0OUJjZ0Vi
        UW5jUVkzdkVNNXRFK2p0eU1MYlNSMnVnNXpJCkF1NEg3WmczMVZQS3ZXMkZaS0l1
        MjYrUmlZU281dXF2a3J0bG9kKytMNTAKLS0tIFFZZG9sL1l3SDFJNzdrUno2MGpq
        Q2pxeUk0NjVmNm0xYkFWUjVEcVl0TG8KZZB/CW2BXzWqjhQ56WDvwRsi+a3RwiK7
        mve0LKToHRTX46TLxADaMdfmqc1qa9nUARdXA/NwpXRK0YtDrwrW2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2022-12-11T09:37:47Z'
  mac: ENC[AES256_GCM,data:NIWtk3QadbN0cqIA18U7hpqzdzEOgAFKEsdgYGEvCwKTNvbYOC0v34gxCIwNwvNSRYZVDkoGDH+cA8fqRdCGu3ho8FOZEqU0uUKHwSlTYnmZ/qWkarPy392fTOctWfPm4okG/0cZeaV7tfW6QiuwxSVrbKikwtkFe/RsI7pNYJI=,iv:GuBJlOMQ7/VTfRV5LpsBtnSwy7btOcKOeZ+20i76ZN0=,tag:rTIN3A3g4fSJJ2NLeUU0YQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.7.3
