---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  releaseName: radarr
  interval: 10m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: radarr
      version: 16.3.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    initContainers:
      update-volume-permission:
        command:
          - sh
          - -c
          - chown -R 568:568 /config
        image: busybox
        securityContext:
          runAsUser: 0
        volumeMounts:
          - mountPath: /config
            name: config
    ingress:
      main:
        enabled: true
        annotations:
          kubernetes.io/tls-acme: 'true'
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/auth-url: http://oauth2-proxy.networking.svc.cluster.local/oauth2/auth
          nginx.ingress.kubernetes.io/auth-signin: ${SECRET_AUTH_URL}
          cert-manager.io/cluster-issuer: letsencrypt-production

        labels: {}
        path: /
        hosts:
          - host: radarr.${SECRET_DOMAIN}
            paths:
              - path: /
        tls:
          - secretName: radarr-cert
            hosts:
              - radarr.${SECRET_DOMAIN}

    env:
      PUID: 1001
      PGID: 1001
      TZ: America/New_York

    probes:
      startup:
        enabled: true

    persistence:
      config:
        enabled: true
        storageClass: ceph-hdd
        accessMode: ReadWriteOnce
        type: pvc
        size: 8Gi
        retain: true

      media:
        enabled: true
        existingClaim: movies
        type: pvc
        mountPath: /media

      downloads:
        enabled: true
        type: pvc
        existingClaim: incoming-movies-sabnzbd
        mountPath: /incoming

    podAnnotations:
      backup.velero.io/backup-volumes: config

    resources:
      # We usually recommend not to specify default resources and to leave this as a conscious
      # choice for the user. This also increases chances charts run on environments with little
      # resources, such as Minikube. If you do want to specify resources, uncomment the following
      # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
      limits:
        cpu: 1000m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 512Mi
    metrics:
      enabled: true
      serviceMonitor:
        interval: 3m
        scrapeTimeout: 1m
      prometheusRule:
        enabled: true
      exporter:
        image:
          repository: ghcr.io/onedr0p/exportarr
          tag: v1.2.3
        env:
          port: 9794
          additionalMetrics: true
          unknownQueueItems: true
