---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: 4c4c4544-0046-4a10-804d-b7c04f484c32
  labels:
    master-node: 'true'
spec:
  accepted: true
  bmc:
    endpoint: 10.0.15.15
    user: sidero
    pass: ${SECRET_ALICE_IPMI_PASSWORD}
  cpu:
    manufacturer: Intel
    version: Intel(R) Xeon(R) CPU           X5690  @ 3.47GHz
  hostname: alice
  system:
    manufacturer: Dell Inc.
    skuNumber: BMMB92S
    version: PowerEdge R710
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda1
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: e4:1d:2d:7e:af:f0
            dhcp: true
            vip:
              ip: 10.0.14.5
    - op: replace
      path: /machine/certSANs
      value:
        - 10.0.14.5
    - op: add
      path: /cluster/allowSchedulingOnControlPlanes
      value: true
    - op: add
      path: /machine/sysctls
      value:
        vm.nr_hugepages: 1024
