---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  name: 4c4c4544-0031-3810-8047-b4c04f433432
  labels:
    worker-node: 'true'
spec:
  pxeBootAlways: true
  accepted: true
  bmc:
    endpoint: 10.0.15.17
    user: sidero
    pass: ${SECRET_PHIL_IPMI_PASSWORD}
  cpu:
    manufacturer: Intel
    version: Intel(R) Xeon(R) CPU E5-2623 v3 @ 3.00GHz
  hostname: phil
  system:
    manufacturer: Dell Inc.
    productName: PowerEdge R530
    version: 418GC42
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sdb1
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: e4:1d:2d:7f:9f:e0
            dhcp: true
    - op: add
      path: /machine/sysctls
      value:
        vm.nr_hugepages: 1024
