---
apiVersion: metal.sidero.dev/v1alpha1
kind: Server
metadata:
  labels:
    master-node: 'true'
  name: 00000000-0000-0000-0000-0cc47a187714
spec:
  accepted: true
  bmc:
    endpoint: 10.0.15.11
  cpu:
    manufacturer: Intel
    version: Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
  hostname: thing1
  system:
    manufacturer: Supermicro
    productName: SYS-628TR-DTR-02-LC019
    serialNumber: S178810X5626992
  configPatches:
    - op: replace
      path: /machine/install/disk
      value: /dev/sda
    - op: add
      path: /machine/network
      value:
        interfaces:
          - deviceSelector:
              hardwareAddr: e4:1d:2d:2c:8b:30
            dhcp: true
            vip:
              ip: 10.0.14.5
    - op: replace
      path: /machine/certSANs
      value:
        - 10.0.14.5
    - op: add
      path: /cluster/allowSchedulingOnControlPlanes
      value: true
    - op: add
      path: /machine/sysctls
      value:
        vm.nr_hugepages: 1024
