---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: blookums-core
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: blookums-kubeconfig
  interval: 10m0s
  dependsOn:
    - name: blookums-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/blookums/core
  prune: true
  validation: client
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-blookums
      - kind: ConfigMap
        name: cluster-settings-blookums
  decryption:
    provider: sops
    secretRef:
      name: sops-age
