---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blookums-metallb-config
  namespace: flux-system
spec:
  kubeConfig:
    secretRef:
      name: blookums-kubeconfig
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./manifests/blookums/apps/networking/metallb/config
  prune: false
  dependsOn:
    - name: blookums-metallb
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: Secret
        name: cluster-secrets-blookums
      - kind: ConfigMap
        name: cluster-settings-blookums
  decryption:
    provider: sops
    secretRef:
      name: sops-age
