---

name: Schedule - Renovate Helm Releases

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: 0 20 * * *

jobs:
  renovate-helm-releases:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Renovate Helm Releases
        uses: k8s-at-home/renovate-helm-releases@v1.4.5
        with:
          cluster-path: ./cluster

      - name: Create pull request for renovatebot helm-release annotations
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: renovate-helm-release-annotations
          delete-branch: true
          title: Update renovatebot helm-release annotations
          signoff: true
          committer: Mike Wilson <hyperbolic2346@users.noreply.github.com>
          author: Mike Wilson <hyperbolic2346@users.noreply.github.com>
          assignees: hyperbolic2346
          commit-message: Update renovatebot helm-release annotations
          body: |
            Add special annotations to HelmReleases inorder for Renovate to pick up new versions of Helm charts
          labels: renovate/helm-release-annotations
